version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-tracker}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      target: deps
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-tracker}?schema=public
      NODE_ENV: development
      PORT: 3000
      HOST_PORT: ${HOST_PORT:-3000}
    ports:
      - '${HOST_PORT:-3000}:${PORT:-3000}'
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./package.json:/app/package.json
      - ./next.config.js:/app/next.config.js
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./public:/app/public
      - ./postcss.config.js:/app/postcss.config.js
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
    command: sh -c "npx prisma generate && npx prisma db push --accept-data-loss && npx prisma db seed && pnpm dev"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
